# Generated by Django 5.1.2 on 2025-01-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='elo',
            new_name='score',
        ),
    ]
