# Generated by Django 5.1.2 on 2025-01-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_bot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
